### ISSUE TITLE
Crash in SAPReallocMem() if thread's MM is not created yet

### ISSUE THREAD

**Issue by michbak** [alan008/sapmm#1]
Hi,

I think `SAPReallocMem()` should check if `tmm` is not null and create thread's MM if needed. Here is how I see it:

```
  ...
  // Next asm block is an inline for: tmm := GetThreadMM;
  asm
    mov eax,TLSOffset
    mov ecx,fs:[$00000018]
    mov eax,[ecx+eax]
    mov tmm, eax
  end;

  // Create thread's MM if needed.
  if tmm = nil then
  begin
    tmm := CreateThreadMM;
  end
  else if mm = tmm then
  begin
    // Realloc inside one thread MM
    ThreadReallocMem(mm, p, size);
    Result := p;
    Exit;
  end;

  // Interthread realloc
  {$IFDEF SAP_STAT}
  InterlockedIncrement(tmm.no_inter_realloc);
  {$ENDIF SAP_STAT}
  Result := InterThreadRealloc(tmm, mm, p, size);
end;
```

Michał.

**Comment by alan008** [comment]
Hi, Michał!
Are you getting any problems with current code? I think, this is strange (or very rare) case, when realloc is the first memory opreation in newly created thread. Usually, memory is first allocated (and thread's MM is created), and only after that realloc may occur.

**Comment by michbak** [comment]
Yes. I do agree it must be very rare, but it does happen in my code. In my case the memory block is allocated in GUI thread and then passed to the calculation thread. In some cases it does happen that the first memory operation in calculation thread is realloc.
The current architecture of my application is a subject to change, but still I think that SAPMM should be immune to such situations.

BTW, SAPMM is great! I've tried many MMs for Delphi and this one is the only fast & stable at the same time!

**Comment by alan008** [comment]
Could you please make a pull request with your change, so I can merge it into the code?

**Comment by alan008** [comment]
Merged your correction, thanks!
